%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Right Camera calibration and distortion parameters (OpenCV)
Camera.fx: 605.575500488281
Camera.fy: 605.200744628906
Camera.cx: 319.330200195312
Camera.cy: 251.158935546875

Camera1.fx: 605.575500488281
Camera1.fy: 605.200744628906
Camera1.cx: 319.330200195312
Camera1.cy: 251.158935546875

# distortion parameters
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# IR projector baseline times fx (aprox.)
Camera.bf: 100.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.0745

# Depth map values factor
RGBD.DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# LiDAR Parameters
#--------------------------------------------------------------------------------------------
# Rotation Translation Matrix from LiDAR to Camera Frame of reference
# Ini aku ambil dari jurnal karena belum tau metode aslinya 
#LiDAR.Tr11: 0
#LiDAR.Tr12: -1
#LiDAR.Tr13: 0
#LiDAR.Tr14: 0.12
#LiDAR.Tr21: 0
#LiDAR.Tr22: 0
#LiDAR.Tr23: -1
#LiDAR.Tr24: 0.05
#LiDAR.Tr31: 1
#LiDAR.Tr32: 0
#LiDAR.Tr33: 0
#LiDAR.Tr34: 0.4

LiDAR.Tr11: 4.276802385584e-04
LiDAR.Tr12: -9.999672484946e-01
LiDAR.Tr13: -8.084491683471e-03
LiDAR.Tr14: -1.198459927713e-02
LiDAR.Tr21: -7.210626507497e-03
LiDAR.Tr22: 8.081198471645e-03
LiDAR.Tr23: -9.999413164504e-01
LiDAR.Tr24: -5.403984729748e-02
LiDAR.Tr31: 9.999738645903e-01
LiDAR.Tr32: 4.859485810390e-04
LiDAR.Tr33: -7.206933692422e-03
LiDAR.Tr34: -2.921968648686e-01

# Option for Upsampling: NearestNeighborPixel, AverageFiltering or InverseDilation
#LiDAR.Method: "NearestNeighborPixel"
#LiDAR.Method: "AverageFiltering"
LiDAR.Method: "InverseDilation"

# Minimum and Maximum Distance to be considered during pointcloud projection
LiDAR.min_dist: 5.0
LiDAR.max_dist: 200.0

### Method Specific Options
# Only Consider the Options for the method you selected, all others may be ignored
# Do not delete entries that are not required, just ignore them.

# For Nearest Neighbor on Pixel Level
LiDAR.MethodNearestNeighborPixel.SearchDistance: 7.0

# For Average Filtering
LiDAR.MethodAverageFiltering.bDoDilationPreprocessing: 1
LiDAR.MethodAverageFiltering.DilationPreprocessing_KernelType: "Diamond"
LiDAR.MethodAverageFiltering.DilationPreprocessing_KernelSize: 3.0
LiDAR.MethodAverageFiltering.KernelSize: 5.0

# For Inverse Dilation
LiDAR.MethodInverseDilation.KernelType: "Diamond"
LiDAR.MethodInverseDilation.KernelSize_u: 5.0 # width of the kernel
LiDAR.MethodInverseDilation.KernelSize_v: 7.0 # height of the kernel; not considered in Diamond mode

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0

#--------------------------------------------------------------------------------------------
# Atlas Parameters
#--------------------------------------------------------------------------------------------
#System.LoadAtlasFromFile: "map_b"
#System.SaveAtlasToFile: "name"
